{{-- =====================================================================
Global UI State — Alpine.store('ui') for shared darkMode, lang, t()
Wrap your page content with <x-ui-state> ... </x-ui-state>
===================================================================== --}}
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.store('ui', {
            darkMode: false,
            lang: 'English',
            loading: false,

            showLoading(ms = 800) {
                this.loading = true;
                setTimeout(() => { this.loading = false; }, ms);
            },

            /* -- i18n translation map -- */
            t(key) {
                const dict = {
                    English: {
                        /* Hero */
                        heroHeadline1: 'Deliver beautifully simple',
                        heroHeadline2: 'service with HelpDesk',
                        heroSubtitle: 'The preferred help desk for customer-first companies.',
                        heroPlaceholder: 'Enter your email',
                        heroTryFree: 'Try for free',
                        heroPrivacy: 'By submitting, I agree to HelpDesk\'s',
                        heroPrivacyLink: 'Privacy Notice',
                        heroInvalidEmail: 'Please enter a valid email address.',
                        heroThankYou: 'Thank you! Check your email.',
                        heroDashboard: 'Go to Dashboard',

                        /* Discover */
                        discoverBadge1: 'Users Love Us',
                        discoverBadge2: 'Happiest Users 2023',
                        discoverTitle: 'Discover HelpDesk',
                        discoverTab_ticketList: 'Ticket list',
                        discoverTab_ticketView: 'Ticket view',
                        discoverTab_automations: 'Automations',
                        discoverTab_reports: 'Reports',
                        discoverCta: 'Sign up free',

                        /* Support Heroes */
                        heroesTitle1: 'We\'re here for you',
                        heroesTitle2: '24/7/365',
                        heroesDescription: 'When you need assistance, you can count on our Support Heroes. They\'re strong, they\'re swift, and they\'ll help you no matter the time!',
                        heroesCta: 'Chat with us',
                        homeSupportHeroesBadge: 'Support Heroes',
                        homeSlaCardTitle: 'SLA Enforcement',
                        homeSlaCardBody: 'Live countdown timers on every ticket. Amber warnings, red alerts on breach.',
                        homeKnowledgeCardTitle: 'Knowledge Base',
                        homeKnowledgeCardBody: 'A full public help center at your subdomain - articles, categories, and search.',
                        homeGetStartedHeading: 'Get Started',
                        homeGetStartedLine1: 'Learn the platform in less than an hour.',
                        homeGetStartedLine2Prefix: 'Become a',
                        homeGetStartedLine2Emphasis: 'power user',
                        homeGetStartedLine2Suffix: 'in less than a day.',
                        homeGetStartedPrimaryCta: 'Get Started',
                        homeGetStartedSecondaryCta: 'Book a Demo',
                        homeSfsTitle: 'Plus, all the little things support teams love',
                        homeSfsAutomationTitle: 'Automation Engine',
                        homeSfsAutomationBody: 'Set conditions once - tickets route, escalate, and notify automatically.',
                        homeSfsTagsTitle: 'Tags & Labels',
                        homeSfsTagsBody: 'Organize every conversation with color-coded tags so nothing falls through the cracks.',
                        homeSfsInboxesTitle: 'Multiple Inboxes',
                        homeSfsInboxesBody: 'Give every department or product its own dedicated place for support.',
                        homeSfsAiTitle: 'AI Copilot',
                        homeSfsAiBody: 'AI reads the ticket, suggests a reply in your tone, and summarizes the full history.',
                        homeSfsReportsTitle: 'Analytics & Reports',
                        homeSfsReportsBody: 'Track team performance, response times, and customer satisfaction at a glance.',
                        homeSfsRoutingTitle: 'Smart Routing',
                        homeSfsRoutingBody: 'Every ticket finds the best available agent instantly - based on category and workload.',
                        homeSfsPreviewAutomationRule: 'Automation Rule',
                        homeSfsPreviewActive: 'Active',
                        homeSfsPreviewWhen: 'WHEN',
                        homeSfsPreviewThen: 'THEN',
                        homeSfsPreviewAssignTo: 'Assign to',
                        homeSfsPreviewBillingTeam: 'Billing Team',
                        homeSfsPreviewRanTimes: 'Ran 248 times',
                        homeSfsPreviewAiCustomerMsg: 'My order #4821 has not arrived. Can you help?',
                        homeSfsPreviewAiSuggestion: 'AI Suggestion',
                        homeSfsPreviewUseReply: 'Use reply',
                        homeSfsPreviewRegenerate: 'Regenerate',
                        homeSfsPreviewTicketQueue: 'Ticket Queue',
                        homeSfsPreviewBreached: 'Breached',
                        homeSfsPreviewPaymentFailed: 'Payment failed',
                        homeSfsPreviewSlaBreachedUrgent: 'SLA breached · Urgent',
                        homeSfsPreviewKbSearch: 'Search knowledge base...',
                        homeSfsPreviewKbArticle1: 'How to pause your subscription',
                        homeSfsPreviewKbMeta1: 'Billing · 2 min read',
                        homeSfsPreviewKbArticle2: 'Reset your password',
                        homeSfsPreviewKbMeta2: 'Account · 1 min read',
                        homeSfsPreviewKbArticle3: 'Tracking your order',
                        homeSfsPreviewKbMeta3: 'Shipping · 3 min read',
                        homeSfsPreviewKbBadge: '24 articles · Available at /kb',
                        homeSfsPreviewReportsHead: 'Team Performance · This Week',
                        homeBeaconAiAssistant: 'AI Assistant',
                        homeBeaconEndChat: 'End chat',
                        homeBeaconAskQuestion: 'Ask a question...',
                        homeBeaconAgentsOnline: '2 agents online',
                        homeBeaconPreviousConversations: 'Previous Conversations',
                        homeBeaconLastUpdatedToday: 'Last updated today',
                        homeSfsTagResolved: 'Resolved',
                        homeSfsTagPending: 'Pending',
                        homeSfsTagBug: 'Bug',
                        homeSfsTagGeneral: 'General',
                        homeSfsTagOnboarding: 'Onboarding',
                        homeSfsPreviewFriendly: 'Friendly',
                        homeSfsPreviewFormal: 'Formal',
                        homeSfsPreviewCantLogin: 'Can\'t login',
                        homeSfsPreviewMinutesLeftHigh: '18 min left · High',
                        homeSfsPreviewAvgReply: 'Avg Reply',
                        homeSfsPreviewResolved: 'Resolved',
                        homeSfsPreviewUrgent: 'Urgent',
                        homeSfsPreviewAccount2fa: 'Can\'t access my account after 2FA',
                        homeSfsPreviewCategoryAccount: 'Category: Account',
                        homeSfsPreviewAssignedSara: 'Assigned to Sara K.',
                        homeSfsPreviewAccountTeamTickets: 'Account Team · 2 open tickets',
                        homeSfsPreviewRoutedIn: 'Routed in',
                        homeBeacon3Billing: 'Billing',
                        homeBeacon3SlaBreachSoon: 'SLA breach in 18 min - respond now',
                        homeBeacon3CustomerSarah: 'Customer · Sarah M.',
                        homeBeacon3CustomerMessage: 'Hi, I was charged twice for my subscription this month and I need this resolved ASAP.',
                        homeBeacon3AgentReply: 'Hi Sarah, I\'m sorry for the double charge. I\'ve started a full refund for the duplicate payment and will confirm once complete.',
                        homeBeacon3Tone: 'Tone:',
                        homeBeacon3Professional: 'Professional',
                        homeBeacon3OpenBreached: 'open · 2 breached',
                        homeBeacon3FilterAll: 'All',
                        homeBeacon3FilterUnassigned: 'Unassigned',
                        homeBeacon3NoAccountNeeded: 'No account needed - just your email',
                        homeBeacon3StepSubmitted: 'Ticket submitted',
                        homeBeacon3StepAssigned: 'Assigned to agent',
                        homeBeacon3StepInProgress: 'In progress',
                        homeBeacon3ReplyToAgent: 'Reply to agent',

                        /* Beacons */
                        beacon1Title: 'Meet Help Desk AI: your embeddable support hub',
                        beacon1Tab1Title: 'Answer instantly with AI',
                        beacon1Tab1Body: 'Let AI handle common questions around the clock - no wait time, no agent needed.',
                        beacon1Tab2Title: 'Keep human help within reach',
                        beacon1Tab2Body: 'Whether you offer live chat, email, or both, your team will always be within two clicks.',
                        beacon1Tab3Title: 'Save customers time',
                        beacon1Tab3Body: 'Allow easy access to previous conversations so customers can pick up where they left off.',
                        beacon1DemoMsg1: 'Hi! I can answer your questions instantly. What do you need help with?',
                        beacon1DemoMsg2: 'What\'s your return policy?',
                        beacon1DemoMsg3: 'You can return any item within 30 days of purchase for a full refund - no questions asked! 🎉',
                        beacon1DemoHuman1: 'Hey Amber! Nikita here. What can I help you with today?',
                        beacon1DemoHuman2: 'Hi there! I\'m wondering about the status of my recent order.',
                        beacon1DemoHuman3: 'The order number is #10283089',
                        beacon2Title: 'Stay organized automatically',
                        beacon2Tab1Title: 'Assign the right person for the job',
                        beacon2Tab1Body: 'Automatically route each ticket to the teammate best suited to solve it quickly.',
                        beacon2Tab2Title: 'Never miss important messages',
                        beacon2Tab2Body: 'Keep urgent customer conversations visible with clear priorities and smart alerts.',
                        beacon2Tab3Title: 'Simplify the queue for your team',
                        beacon2Tab3Body: 'Help everyone get more efficient with custom Views that group conversations.',
                        beacon3TitlePrefix: 'Everything your support team needs',
                        beacon3TitleEmphasis: 'in one place',
                        beacon3Tab1Title: 'AI Copilot for every agent',
                        beacon3Tab1Body: 'AI reads the full conversation, generates a suggested reply in your chosen tone, and summarizes the entire ticket history so agents move faster without missing context.',
                        beacon3Tab2Title: 'Smart routing, live SLA tracking',
                        beacon3Tab2Body: 'Every ticket is auto-assigned to the best available agent, while SLA countdowns and breach alerts keep response times on track.',
                        beacon3Tab3Title: 'Zero friction for customers',
                        beacon3Tab3Body: 'No account needed. Customers verify by email, receive a tracking link, and follow updates or reply from any device.',

                        /* Navbar */
                        products: 'Products',
                        solutions: 'Solutions',
                        resources: 'Resources',
                        pricing: 'Pricing',
                        companyMenu: 'Company',
                        tryFree: 'Sign up free',
                        viewDemo: 'Login',
                        dashboard: 'Dashboard',
                        platform: 'Platform',
                        platformOverview: 'Platform overview',
                        integrations: 'Integrations',
                        latestInnovations: 'Latest innovations',
                        appMarketplace: 'App marketplace',
                        developers: 'Developers',
                        trending: 'Trending',
                        trendItem1: 'HD AI Virtual Summit 2026',
                        trendDesc1: 'A global event for leaders in CX, IT, HR.',
                        trendItem2: 'Hidden costs of complexity',
                        trendDesc2: 'Uncover the IT complexity tax costing your business.',
                        trendItem3: 'HD partners with top teams',
                        trendDesc3: 'Discover how HD is powering global partnerships.',
                        navProductFeatureTitle: 'Meet Freddy AI',
                        navProductFeatureBadge: 'NEW',
                        navProductFeatureDescription: 'Agentic AI that reasons, acts and resolves',
                        navProductFeatureCta: 'Explore Freddy AI',
                        productCard1Title: 'Freshservice',
                        productCard1Desc: 'Modern IT and employee service desk.',
                        productCard2Title: 'Freshdesk Omni',
                        productCard2Desc: 'Omnichannel customer service powered by AI.',
                        productCard3Title: 'Freshdesk',
                        productCard3Desc: 'Simple support ticketing for growing teams.',
                        productLearnMore: 'Learn more',
                        productFeatured: 'Featured',
                        productTour: 'Product tour',
                        productTourDesc1: 'See how teams resolve incidents faster.',
                        productTourDesc2: 'Explore automation for every support channel.',
                        productTourDesc3: 'Discover a faster ticket workflow in minutes.',
                        productWhatsNew: 'What\'s new',
                        productUpdateDesc: 'Latest AI improvements and integrations.',
                        productAllTrials: 'View all product trials',
                        companyAbout: 'About us',
                        companyAboutDesc: 'Learn our mission, story, and values.',
                        companyCareers: 'Careers',
                        companyCareersDesc: 'Build products that help teams serve better.',
                        companyHelpCenterDesc: 'Browse guides, FAQs, and support resources.',
                        companyContactDesc: 'Reach our team for sales or support questions.',
                        companyPartnerDesc: 'Grow with our global partner network.',
                        navResourceFeatureTitle: 'Learn with practical resources',
                        navResourceFeatureDescription: 'Playbooks, docs, and guides to launch better support workflows.',
                        navResourceFeatureCta: 'Explore resources',
                        byTeam: 'By Team',
                        customerService: 'Customer Service',
                        itSupport: 'IT Support',
                        hrTeams: 'HR Teams',
                        salesTeams: 'Sales Teams',
                        bySize: 'By Company Size',
                        enterprise: 'Enterprise',
                        midMarket: 'Mid-market',
                        smallBusiness: 'Small Business',
                        startups: 'Startups',
                        learn: 'Learn',
                        blog: 'Blog',
                        documentation: 'Documentation',
                        webinars: 'Webinars',
                        academy: 'Academy',
                        connect: 'Connect',
                        community: 'Community',
                        events: 'Events',
                        partnerProgram: 'Partner program',
                        support: 'Support',

                        /* Utility Bar */
                        utilitySignIn: 'Sign in',
                        utilityLogout: 'Logout',
                        utilityHelpCenter: 'Help Desk center',
                        utilityCompany: 'Company',
                        utilityContactUs: 'Contact us',

                        /* Footer */
                        footerTagline: 'Modern helpdesk for modern teams.',
                        footerProducts: 'Products',
                        footerPlatformOverview: 'Platform Overview',
                        footerIntegrations: 'Integrations',
                        footerMarketplace: 'App Marketplace',
                        footerDevelopers: 'Developers',
                        footerSolutions: 'Solutions',
                        footerCustomerService: 'Customer Service',
                        footerItSupport: 'IT Support',
                        footerHrTeams: 'HR Teams',
                        footerSalesTeams: 'Sales Teams',
                        footerResources: 'Resources',
                        footerBlog: 'Blog',
                        footerDocumentation: 'Documentation',
                        footerWebinars: 'Webinars',
                        footerCommunity: 'Community',
                        footerCompany: 'Company',
                        footerAbout: 'About Us',
                        footerCareers: 'Careers',
                        footerContact: 'Contact',
                        footerPrivacy: 'Privacy Policy',
                        footerRights: 'All rights reserved.',
                        footerColProduct: 'Product',
                        footerLinkDashboard: 'Dashboard',
                        footerLinkFeatures: 'Features',
                        footerLinkDiscover: 'Discover',
                        footerLinkFooter: 'Footer',
                        footerColResources: 'Resources',
                        footerLinkGettingStarted: 'Getting Started',
                        footerLinkAutomationIdeas: 'Automation Ideas',
                        footerLinkCustomerStories: 'Customer Stories',
                        footerLinkBrandAssets: 'Brand Assets',
                        footerColQuickLinks: 'Quick Links',
                        footerLinkHome: 'Home',
                        footerLinkProductTour: 'Product Tour',
                        footerLinkTestimonials: 'Testimonials',
                        footerLinkFooterLayout: 'Footer Layout',
                        footerColCompanySupport: 'Company & Support',
                        footerLinkAbout: 'About',
                        footerLinkHelpCenter: 'Help Center',
                        footerLinkContact: 'Contact',
                        footerLinkStatus: 'Status',
                        footerBrand: 'Help Desk',

                        /* Notification banner */
                        notificationBannerLine: 'We\'d love to help. Talk to our',
                        notificationBannerStrong: 'support heroes.',
                        notificationBannerCta: 'Chat now ->',
                        notificationBannerDismiss: 'Dismiss notification',

                        /* Chatbot widget */
                        chatbotWelcome1: 'Welcome to our Helpdesk! We\'re here to assist you with any questions or issues you might have. How can we help you today?',
                        chatbotWelcome2: 'Hello there! Need a hand? We\'re ready to help you find the best solutions right away.',
                        chatbotWelcome3: 'Welcome back! We\'ve been expecting you. What can our support team do for you today?',
                        chatbotWelcome4: 'Hi! Thanks for reaching out. Let us know how we can make your day a little bit easier.',
                        chatbotWelcome5: 'Greetings! We\'re here to provide you with fast and friendly support. What\'s on your mind?',
                        chatbotNoConversationsTitle: 'No conversations yet',
                        chatbotNoConversationsBody: 'Tap below to start a conversation.<br>We\'ll help you right away!',
                        chatbotStartedPrefix: 'Started',
                        chatbotEnded: 'Ended',
                        chatbotRemoveConversation: 'Remove conversation',
                        chatbotNewConversation: 'New conversation',
                        chatbotBuiltWith: 'BUILT WITH HELPDESK AI',
                        chatbotRepliesFast: 'Typically replies instantly',
                        chatbotQuickActions: 'Quick actions',
                        chatbotQuickReply1: 'How does the ticketing system work?',
                        chatbotQuickReply2: 'Can I try it for free?',
                        chatbotQuickReply3: 'What integrations do you support?',
                        chatbotQuickReply4: 'Tell me about pricing',
                        chatbotInputPlaceholder: 'Type your message...',

                        /* About page */
                        aboutTypewriter: 'About us',
                        aboutHeroTitle: 'Building support software that feels human at scale',
                        aboutHeroDescription: 'HelpDesk was created to remove chaos from customer service. We built one platform where teams can route tickets intelligently, respond with AI-assisted speed, and close every conversation with confidence.',
                        aboutHeroCtaPrimary: 'Talk to our team',
                        aboutHeroCtaSecondary: 'Explore help center',
                        aboutPillar1Title: 'Global reach',
                        aboutPillar1Body: 'Teams across every timezone trust HelpDesk to keep operations running.',
                        aboutPillar2Title: 'Built for scale',
                        aboutPillar2Body: 'Enterprise-grade architecture designed from day one for growth.',
                        aboutPillar3Title: 'Privacy first',
                        aboutPillar3Body: 'Your data stays yours with strict isolation and full transparency.',
                        aboutPillar4Title: 'Human-centered',
                        aboutPillar4Body: 'AI that empowers agents, never replaces the human connection.',
                        aboutStoryTitle: 'Our story',
                        aboutStoryBody1: 'We started with one observation: support teams were managing mission-critical customer work across disconnected inboxes, spreadsheets, and fragile workflows. Issues were delayed, ownership was unclear, and leaders had no reliable visibility. So we reimagined support as a single operating system.',
                        aboutStoryBody2: 'Today, companies launch HelpDesk in hours, not months. Admins define categories, SLAs, automation rules, and team groups. Agents get contextual AI suggestions and instant ticket summaries. Customers receive updates without account friction. Every action is auditable, measurable, and built for scale.',
                        aboutDifferenceTitle: 'What makes HelpDesk different',
                        aboutDifference1Title: 'Multi-tenant isolation',
                        aboutDifference1Body: 'Each company has its own subdomain, data scope, and configuration model with strict separation by design.',
                        aboutDifference2Title: 'No-login customer experience',
                        aboutDifference2Body: 'Customers verify by email and continue through a tracking link, reducing drop-off and friction.',
                        aboutDifference3Title: 'Smart routing engine',
                        aboutDifference3Body: 'Tickets route by category, subcategory, specialties, workload, and availability in near real time.',
                        aboutDifference4Title: 'AI as copilot, not replacement',
                        aboutDifference4Body: 'Agents stay in control while AI handles summaries, suggestions, and repetitive drafting tasks.',
                        aboutGrowthTitle: 'How teams grow with us',
                        aboutGrowthPhase1Label: 'Phase 1',
                        aboutGrowthPhase1Title: 'Launch in days',
                        aboutGrowthPhase1Body: 'Admins run onboarding, configure ticket categories and SLA policy, then embed the form widget with one script.',
                        aboutGrowthPhase2Label: 'Phase 2',
                        aboutGrowthPhase2Title: 'Automate operations',
                        aboutGrowthPhase2Body: 'Rules assign tickets, trigger alerts, and escalate SLA risks automatically while leaders monitor live dashboards.',
                        aboutGrowthPhase3Label: 'Phase 3',
                        aboutGrowthPhase3Title: 'Optimize performance',
                        aboutGrowthPhase3Body: 'Teams refine workflows through analytics, category health reports, and agent leaderboards that expose bottlenecks quickly.',
                        aboutNoteTitle: 'A note from our team',
                        aboutNoteBody1: 'We design HelpDesk to feel clear, fast, and dependable from day one. We care about operational details: handoff quality, response consistency, escalation visibility, and long-term maintainability. Your support team should never feel held back by tooling. It should feel amplified.',
                        aboutNoteBody2: 'Whether you are launching your first support operation or scaling a multi-region service organization, our product and customer success teams are here to help you build workflows that last.',
                        aboutVisionTitle: 'Deep product vision',
                        aboutVisionBody1: 'We believe support systems should not just track requests, but coordinate outcomes. That means every interaction needs structured context, clear ownership, actionable timelines, and measurable quality signals. In HelpDesk, every ticket is tied to categories, priorities, SLA clocks, and operational routing logic so teams can move fast without losing precision.',
                        aboutVisionBody2: 'As support volume grows, complexity grows faster than headcount. We designed HelpDesk to absorb that complexity through smart defaults and configurable automation. Assignment rules, escalation triggers, SLA alerts, and lifecycle actions work together so teams spend less time orchestrating work manually and more time solving customer problems.',
                        aboutVisionBody3: 'We also care deeply about experience quality for every role. Admins need control and visibility. Agents need speed and context. Customers need frictionless progress. This is why we built no-login ticket tracking, AI copilot summaries, in-thread collaboration notes, and knowledge tools into a single workflow that remains clear even under pressure.',
                        aboutInfrastructureTitle: 'How we design support infrastructure',
                        aboutInfrastructure1Title: 'Reliability first',
                        aboutInfrastructure1Body: 'Workflows are designed for predictable execution. Assignment, escalation, notification, and closure logic run in a deterministic sequence so teams can trust the system in high-volume periods.',
                        aboutInfrastructure2Title: 'Operator efficiency',
                        aboutInfrastructure2Body: 'Agents see context instantly through AI summaries, clear ticket states, and direct access to knowledge base references. This reduces response time and minimizes unnecessary back-and-forth.',
                        aboutInfrastructure3Title: 'Visible outcomes',
                        aboutInfrastructure3Body: 'Leadership gets full operational insight through report views, SLA health, category-level trends, and export-ready datasets that support both daily triage and quarterly planning.',
                        aboutCultureTitle: 'Inside our global support culture',
                        aboutCultureBody: 'We operate as one distributed team across regions, with shared quality standards and local execution flexibility. Our product, success, and engineering groups collaborate continuously on escalation playbooks, workflow templates, and knowledge architecture so customers receive consistent support outcomes regardless of timezone.',
                        aboutCommitmentTitle: 'Our commitment',
                        aboutCommitmentBody1: 'We commit to building support software that remains fast, observable, and adaptable as your organization grows. We ship features that reduce operational drag, not just add interface complexity. Every release is evaluated against real support workflows: ticket ownership, response quality, queue health, and customer closure satisfaction.',
                        aboutCommitmentBody2: 'We commit to transparency in how automation runs and how AI suggestions are generated in context. Teams should be able to understand and control the system, not guess at its behavior. That is why we emphasize explicit conditions, clear rule outcomes, and robust reporting across tickets, categories, agents, and SLA performance.',
                        aboutCommitmentBody3: 'We commit to partnership. Our team supports implementation strategy, migration planning, and long-term optimization so your support operation can continuously improve over time, not only at launch.',

                        /* Contact page */
                        contactTypewriter: 'Contact',
                        contactHeroTitle: 'Let us help you launch better support faster',
                        contactHeroDescription: 'Tell us what you need, and our team will guide you through setup, migration, automation strategy, and widget embedding.',
                        contactFormTitle: 'Send a message',
                        contactFormRequiredNote: 'Fields marked with * are required.',
                        contactSuccessMessage: 'Message sent successfully. We will get back to you shortly.',
                        contactFieldName: 'Full name *',
                        contactFieldNamePlaceholder: 'Jane Doe',
                        contactFieldEmail: 'Work email *',
                        contactFieldEmailPlaceholder: 'jane@company.com',
                        contactFieldCompany: 'Company name *',
                        contactFieldCompanyPlaceholder: 'Acme Inc',
                        contactFieldTeamSize: 'Team size',
                        contactTeamSizeOption0: 'Select an option',
                        contactTeamSizeOption1: '1-5 agents',
                        contactTeamSizeOption2: '6-20 agents',
                        contactTeamSizeOption3: '21-50 agents',
                        contactTeamSizeOption4: '50+ agents',
                        contactFieldTopic: 'Topic *',
                        contactTopicOption0: 'Choose a topic',
                        contactTopicOption1: 'Book a product demo',
                        contactTopicOption2: 'Migration and onboarding',
                        contactTopicOption3: 'Pricing and plans',
                        contactTopicOption4: 'Technical support',
                        contactFieldMessage: 'Message *',
                        contactFieldMessagePlaceholder: 'Tell us about your support goals, ticket volume, and current workflow.',
                        contactResponseNote: 'We respond within one business day.',
                        contactSubmit: 'Send message',
                        contactSalesTitle: 'Talk to sales',
                        contactSalesBody: 'For pricing and implementation planning.',
                        contactSupportTitle: 'Customer support',
                        contactSupportBody: 'Existing customers can get fast help from our support team.',
                        contactChecklistTitle: 'Fast start checklist',
                        contactChecklist1: '1. Share your current ticket volume and channels.',
                        contactChecklist2: '2. We map categories, SLAs, and automation rules.',
                        contactChecklist3: '3. Your widgets go live with one script tag.',
                        contactOfficesTitle: 'Our offices around the world',
                        contactWhyTitle: 'Why teams contact us before launching',
                        contactWhyBody1: 'Most teams reach out when they are replacing fragmented support workflows and need a reliable rollout plan. We help define priority matrixes, queue ownership, and escalation boundaries before your first live ticket. This avoids rework after launch and gives agents a cleaner, more confident first week in production.',
                        contactWhyBody2: 'We also map your customer journey end-to-end: submission points, response templates, auto-replies, SLA thresholds, and closure policy. The result is a support operation that feels consistent across channels and clear to every stakeholder from day one.',
                        contactAfterTitle: 'What happens after you reach out',
                        contactAfter1Title: 'Discovery call',
                        contactAfter1Body: 'We review your channels, expected volume, team structure, and response targets to design a practical rollout.',
                        contactAfter2Title: 'Configuration plan',
                        contactAfter2Body: 'Categories, SLAs, automation rules, and widget branding are prepared to match your exact workflow.',
                        contactAfter3Title: 'Go-live support',
                        contactAfter3Body: 'We stay with your team through launch, monitor first traffic, and tune routing or response flows where needed.',

                        /* Help center page */
                        helpTypewriter: 'Help Center',
                        helpHeroTitle: 'Answers for admins, agents, and customers in one place',
                        helpHeroDescription: 'Learn how HelpDesk handles ticket routing, AI copilot, SLA automation, embeddable widgets, and reporting workflows.',
                        helpSearchLabel: 'Search answers',
                        helpSearchPlaceholder: 'Try: SLA, automation, chatbot, ticket routing',
                        helpPopularAnswersTitle: 'Popular answers',
                        helpShowMoreAnswers: 'Show 10 more answers',
                        helpJourneyTitle: 'Ticket journey',
                        helpJourney1: '1. Customer submits issue via widget.',
                        helpJourney2: '2. Automation routes to group + best agent.',
                        helpJourney3: '3. Agent receives AI summary and suggestion.',
                        helpJourney4: '4. Resolution starts auto-close lifecycle.',
                        helpRoleWorkflowsTitle: 'Role-based workflows',
                        helpRoleAdmin: 'Admin: setup categories, SLA, groups, and rules.',
                        helpRoleAgent: 'Agent: handle queue, notes, replies, and KB links.',
                        helpRoleCustomer: 'Customer: verify email and track without login.',
                        helpAssistanceTitle: 'Need direct assistance?',
                        helpAssistanceBody: 'For account setup, migration, and custom workflows, reach our team.',
                        helpAssistancePrimaryCta: 'Contact team',
                        helpAssistanceSecondaryCta: 'Email support',
                        helpLifecycleTitle: 'Complete support lifecycle in one platform',
                        helpLifecycleBody1: 'HelpDesk is designed to handle the full journey from submission to archive. New issues enter through your branded widget, get categorized and prioritized, route to the right queue, and receive action in minutes. Agents collaborate with private notes, AI suggestions, and knowledge references while customers stay updated through email and tracking links. Once resolved, the lifecycle continues with reminder windows, auto-close, linked reopen flows, and long-term retention policies that keep your dataset clean and searchable.',
                        helpLifecycleBody2: 'This approach reduces operational fragmentation. Instead of jumping between tools for routing, collaboration, SLA visibility, and customer communication, every team role works in one place with consistent state and a shared source of truth.',
                        helpPlaybooksTitle: 'Operational playbooks for every role',
                        helpPlaybookAdminTitle: 'Admin playbook',
                        helpPlaybookAdminBody: 'Configure categories, SLA tiers, assignment rules, and notification policies. Monitor breaches live and optimize team throughput from centralized reports.',
                        helpPlaybookAgentTitle: 'Agent playbook',
                        helpPlaybookAgentBody: 'Pick from priority-sorted queues, review AI context summary, compose response with optional suggestions, attach files, insert knowledge links, and close with confidence.',
                        helpPlaybookCustomerTitle: 'Customer playbook',
                        helpPlaybookCustomerBody: 'Submit issue without signup, verify by email, follow progress from tracking link, reply from inbox, and receive clear updates throughout each status change.',
                        helpFaq1Q: 'How does customer support work without customer login?',
                        helpFaq1A: 'Customers submit a ticket from the website widget, verify their email, and receive a tracking link. They can follow updates and reply directly from that flow without creating an account.',
                        helpFaq2Q: 'How are tickets routed to the right people?',
                        helpFaq2A: 'The automation engine applies rules using category, subcategory, priority, assigned group, and availability. Then it picks the most suitable agent based on specialties and workload.',
                        helpFaq3Q: 'What does AI Copilot do for agents?',
                        helpFaq3A: 'AI reads the full conversation, generates a concise summary, and suggests editable replies in the selected tone. Agents can regenerate, refine, or dismiss suggestions instantly.',
                        helpFaq4Q: 'How does SLA tracking prevent missed deadlines?',
                        helpFaq4A: 'Each ticket gets a due time by priority policy. Live countdowns show risk status, and breach notifications are sent to assigned agents and admins when thresholds are hit.',
                        helpFaq5Q: 'Can administrators configure automation without code?',
                        helpFaq5A: 'Yes. Admins create condition-action rules from a visual setup panel. They can assign agents/groups, adjust priority, trigger auto-replies, and escalate based on SLA or VIP rules.',
                        helpFaq6Q: 'What lifecycle automation happens after ticket resolution?',
                        helpFaq6A: 'Resolved tickets trigger customer notifications, 24-hour warning reminders, and 48-hour auto-close logic. Closed tickets can reopen through linked flow windows, then archive automatically.',
                        helpFaq7Q: 'How does the knowledge base help agents and customers?',
                        helpFaq7A: 'Customers can browse/search public articles under /kb. Agents can search knowledge base content directly in ticket reply tools and insert links without leaving the conversation.',
                        helpFaq8Q: 'Which widgets can be embedded on our website?',
                        helpFaq8A: 'HelpDesk provides a Form Widget, AI Chatbot Widget, and KB Search Widget. Each uses script-based embed codes and is managed from one integrations area.',
                        helpFaq9Q: 'How is data isolated in multi-tenant mode?',
                        helpFaq9A: 'Every company runs in its own subdomain and scoped dataset. Tickets, customers, settings, and analytics remain isolated with no cross-company access.',
                        helpFaq10Q: 'What reports are available for performance analysis?',
                        helpFaq10A: 'Reports include overview trends, agent performance, ticket analysis, and category health. Teams can export insights to CSV/PDF and monitor leaderboard and resolution behavior.',
                        helpFaq11Q: 'Can agents bulk update multiple tickets at once?',
                        helpFaq11A: 'Yes. Agents and admins can bulk assign owners, change status, adjust priority, and perform batch actions from filtered list views to speed up queue maintenance.',
                        helpFaq12Q: 'How do saved views work for repetitive queue filters?',
                        helpFaq12A: 'Any advanced filter combination can be saved as a named view. Teams can reopen those views instantly to track categories, breach-risk queues, or agent-specific workloads.',
                        helpFaq13Q: 'How are internal notes separated from customer replies?',
                        helpFaq13A: 'Internal notes are stored in the same ticket timeline but marked as private. They are visible to agents/admins only and never sent to customers.',
                        helpFaq14Q: 'Can we use role-based permissions across teams?',
                        helpFaq14A: 'Yes. Admins can control agent capabilities, restrict sensitive actions, and scope access by role or group to keep operations consistent and secure.',
                        helpFaq15Q: 'How does VIP customer routing work?',
                        helpFaq15A: 'VIP conditions can trigger priority overrides, specific routing groups, and custom notifications so high-value customers receive faster and more specialized handling.',
                        helpFaq16Q: 'Can we customize ticket fields in the form widget?',
                        helpFaq16A: 'Admins can configure visible fields, required flags, category/subcategory controls, phone requirements, and default values from the widget settings panel.',
                        helpFaq17Q: 'What happens if no agent is available at ticket creation?',
                        helpFaq17A: 'The ticket remains unassigned, routing intent is preserved, and admins are notified immediately so coverage gaps can be resolved without losing request context.',
                        helpFaq18Q: 'How do notification preferences work per agent?',
                        helpFaq18A: 'Each agent can configure which events they receive. Notifications are grouped by type and date, with dedicated SLA-breach views for rapid triage.',
                        helpFaq19Q: 'Can teams export data for audits and executive reviews?',
                        helpFaq19A: 'Yes. Ticket lists, performance views, and category reports can be exported as CSV or PDF for monthly governance, planning, and compliance reviews.',
                        helpFaq20Q: 'How does the chatbot hand off to ticket creation?',
                        helpFaq20A: 'If the chatbot cannot resolve within configured turns, it offers a guided ticket handoff preserving context so customers continue without restarting their issue description.',
                    },
                    French: {
                        /* Hero */
                        heroHeadline1: 'Offrez un service',
                        heroHeadline2: 'simple et élégant avec HelpDesk',
                        heroSubtitle: 'Le helpdesk préféré des entreprises centrées sur le client.',
                        heroPlaceholder: 'Entrez votre e-mail',
                        heroTryFree: 'Essayer gratuitement',
                        heroPrivacy: 'En soumettant, j\'accepte la',
                        heroPrivacyLink: 'Politique de confidentialité',
                        heroInvalidEmail: 'Veuillez entrer une adresse e-mail valide.',
                        heroThankYou: 'Merci ! Vérifiez votre e-mail.',
                        heroDashboard: 'Aller au tableau de bord',

                        /* Discover */
                        discoverBadge1: 'Les utilisateurs nous adorent',
                        discoverBadge2: 'Utilisateurs les plus heureux 2023',
                        discoverTitle: 'Découvrez HelpDesk',
                        discoverTab_ticketList: 'Liste des tickets',
                        discoverTab_ticketView: 'Vue du ticket',
                        discoverTab_automations: 'Automatisations',
                        discoverTab_reports: 'Rapports',
                        discoverCta: 'Inscription gratuite',

                        /* Support Heroes */
                        heroesTitle1: 'Nous sommes l\u00e0 pour vous',
                        heroesTitle2: '24h/24, 7j/7, 365j/an',
                        heroesDescription: 'Quand vous avez besoin d\u2019aide, comptez sur nos H\u00e9ros du Support. Ils sont forts, rapides et vous aideront \u00e0 tout moment\u00a0!',
                        heroesCta: 'Discutez avec nous',
                        homeSupportHeroesBadge: 'H\u00e9ros du support',
                        homeSlaCardTitle: 'Application des SLA',
                        homeSlaCardBody: 'Comptes \u00e0 rebours en direct sur chaque ticket. Avertissements ambre, alertes rouges en cas de d\u00e9passement.',
                        homeKnowledgeCardTitle: 'Base de connaissances',
                        homeKnowledgeCardBody: 'Un centre d\'aide public complet sur votre sous-domaine - articles, cat\u00e9gories et recherche.',
                        homeGetStartedHeading: 'Commencer',
                        homeGetStartedLine1: 'Prenez en main la plateforme en moins d\'une heure.',
                        homeGetStartedLine2Prefix: 'Devenez un',
                        homeGetStartedLine2Emphasis: 'utilisateur expert',
                        homeGetStartedLine2Suffix: 'en moins d\'une journ\u00e9e.',
                        homeGetStartedPrimaryCta: 'Commencer',
                        homeGetStartedSecondaryCta: 'R\u00e9server une d\u00e9mo',
                        homeSfsTitle: 'Et toutes les petites choses que les \u00e9quipes support adorent',
                        homeSfsAutomationTitle: 'Moteur d\'automatisation',
                        homeSfsAutomationBody: 'D\u00e9finissez les conditions une fois - les tickets sont rout\u00e9s, escalad\u00e9s et notifi\u00e9s automatiquement.',
                        homeSfsTagsTitle: 'Tags et libell\u00e9s',
                        homeSfsTagsBody: 'Organisez chaque conversation avec des tags color\u00e9s pour que rien ne passe entre les mailles du filet.',
                        homeSfsInboxesTitle: 'Bo\u00eetes de r\u00e9ception multiples',
                        homeSfsInboxesBody: 'Donnez \u00e0 chaque \u00e9quipe ou produit son espace support d\u00e9di\u00e9.',
                        homeSfsAiTitle: 'Copilote IA',
                        homeSfsAiBody: 'L\'IA lit le ticket, sugg\u00e8re une r\u00e9ponse selon votre ton, et r\u00e9sume tout l\'historique.',
                        homeSfsReportsTitle: 'Analytique et rapports',
                        homeSfsReportsBody: 'Suivez la performance \u00e9quipe, les temps de r\u00e9ponse et la satisfaction client en un coup d\'oeil.',
                        homeSfsRoutingTitle: 'Routage intelligent',
                        homeSfsRoutingBody: 'Chaque ticket trouve instantan\u00e9ment le meilleur agent disponible selon la cat\u00e9gorie et la charge.',
                        homeSfsPreviewAutomationRule: 'R\u00e8gle d\'automatisation',
                        homeSfsPreviewActive: 'Actif',
                        homeSfsPreviewWhen: 'QUAND',
                        homeSfsPreviewThen: 'ALORS',
                        homeSfsPreviewAssignTo: 'Assigner \u00e0',
                        homeSfsPreviewBillingTeam: '\u00c9quipe facturation',
                        homeSfsPreviewRanTimes: 'Ex\u00e9cut\u00e9 248 fois',
                        homeSfsPreviewAiCustomerMsg: 'Ma commande #4821 n\'est pas arriv\u00e9e. Pouvez-vous aider?',
                        homeSfsPreviewAiSuggestion: 'Suggestion IA',
                        homeSfsPreviewUseReply: 'Utiliser',
                        homeSfsPreviewRegenerate: 'R\u00e9g\u00e9n\u00e9rer',
                        homeSfsPreviewTicketQueue: 'File de tickets',
                        homeSfsPreviewBreached: 'd\u00e9pass\u00e9s',
                        homeSfsPreviewPaymentFailed: 'Paiement \u00e9chou\u00e9',
                        homeSfsPreviewSlaBreachedUrgent: 'SLA d\u00e9pass\u00e9 · Urgent',
                        homeSfsPreviewKbSearch: 'Rechercher dans la base de connaissances...',
                        homeSfsPreviewKbArticle1: 'Comment suspendre votre abonnement',
                        homeSfsPreviewKbMeta1: 'Facturation · 2 min de lecture',
                        homeSfsPreviewKbArticle2: 'R\u00e9initialiser votre mot de passe',
                        homeSfsPreviewKbMeta2: 'Compte · 1 min de lecture',
                        homeSfsPreviewKbArticle3: 'Suivre votre commande',
                        homeSfsPreviewKbMeta3: 'Livraison · 3 min de lecture',
                        homeSfsPreviewKbBadge: '24 articles · Disponible sur /kb',
                        homeSfsPreviewReportsHead: 'Performance d\'\u00e9quipe · Cette semaine',
                        homeBeaconAiAssistant: 'Assistant IA',
                        homeBeaconEndChat: 'Terminer le chat',
                        homeBeaconAskQuestion: 'Posez une question...',
                        homeBeaconAgentsOnline: '2 agents en ligne',
                        homeBeaconPreviousConversations: 'Conversations pr\u00e9c\u00e9dentes',
                        homeBeaconLastUpdatedToday: 'Derni\u00e8re mise \u00e0 jour aujourd\'hui',
                        homeSfsTagResolved: 'R\u00e9solu',
                        homeSfsTagPending: 'En attente',
                        homeSfsTagBug: 'Bug',
                        homeSfsTagGeneral: 'G\u00e9n\u00e9ral',
                        homeSfsTagOnboarding: 'Onboarding',
                        homeSfsPreviewFriendly: 'Amical',
                        homeSfsPreviewFormal: 'Formel',
                        homeSfsPreviewCantLogin: 'Impossible de se connecter',
                        homeSfsPreviewMinutesLeftHigh: '18 min restantes · \u00c9lev\u00e9',
                        homeSfsPreviewAvgReply: 'R\u00e9ponse moy.',
                        homeSfsPreviewResolved: 'R\u00e9solu',
                        homeSfsPreviewUrgent: 'Urgent',
                        homeSfsPreviewAccount2fa: 'Impossible d\'acc\u00e9der au compte apr\u00e8s 2FA',
                        homeSfsPreviewCategoryAccount: 'Cat\u00e9gorie: Compte',
                        homeSfsPreviewAssignedSara: 'Assign\u00e9 \u00e0 Sara K.',
                        homeSfsPreviewAccountTeamTickets: '\u00c9quipe Compte · 2 tickets ouverts',
                        homeSfsPreviewRoutedIn: 'Rout\u00e9 en',
                        homeBeacon3Billing: 'Facturation',
                        homeBeacon3SlaBreachSoon: 'SLA d\u00e9pass\u00e9 dans 18 min - r\u00e9pondez maintenant',
                        homeBeacon3CustomerSarah: 'Cliente · Sarah M.',
                        homeBeacon3CustomerMessage: 'Bonjour, j\'ai \u00e9t\u00e9 factur\u00e9e deux fois ce mois-ci pour mon abonnement et j\'ai besoin d\'une r\u00e9solution rapide.',
                        homeBeacon3AgentReply: 'Bonjour Sarah, d\u00e9sol\u00e9 pour la double facturation. J\'ai lanc\u00e9 un remboursement complet du paiement en double et je vous confirmerai d\u00e8s que c\'est finalis\u00e9.',
                        homeBeacon3Tone: 'Ton :',
                        homeBeacon3Professional: 'Professionnel',
                        homeBeacon3OpenBreached: 'ouverts · 2 d\u00e9pass\u00e9s',
                        homeBeacon3FilterAll: 'Tous',
                        homeBeacon3FilterUnassigned: 'Non assign\u00e9s',
                        homeBeacon3NoAccountNeeded: 'Aucun compte requis - juste votre e-mail',
                        homeBeacon3StepSubmitted: 'Ticket soumis',
                        homeBeacon3StepAssigned: 'Assign\u00e9 \u00e0 un agent',
                        homeBeacon3StepInProgress: 'En cours',
                        homeBeacon3ReplyToAgent: 'R\u00e9pondre \u00e0 l\'agent',

                        /* Beacons */
                        beacon1Title: 'D\u00e9couvrez Help Desk AI: votre hub support int\u00e9grable',
                        beacon1Tab1Title: 'R\u00e9pondez instantan\u00e9ment avec l\'IA',
                        beacon1Tab1Body: 'Laissez l\'IA traiter les questions courantes 24h/24 - sans attente, sans agent.',
                        beacon1Tab2Title: 'Gardez l\'aide humaine \u00e0 port\u00e9e de main',
                        beacon1Tab2Body: 'Que vous proposiez chat en direct, e-mail, ou les deux, votre \u00e9quipe reste \u00e0 deux clics.',
                        beacon1Tab3Title: 'Faites gagner du temps \u00e0 vos clients',
                        beacon1Tab3Body: 'Permettez l\'acc\u00e8s facile aux conversations pr\u00e9c\u00e9dentes pour reprendre l\u00e0 o\u00f9 ils s\'\u00e9taient arr\u00eat\u00e9s.',
                        beacon1DemoMsg1: 'Bonjour! Je peux r\u00e9pondre instantan\u00e9ment \u00e0 vos questions. De quoi avez-vous besoin?',
                        beacon1DemoMsg2: 'Quelle est votre politique de retour?',
                        beacon1DemoMsg3: 'Vous pouvez retourner tout article sous 30 jours pour un remboursement complet - sans questions! 🎉',
                        beacon1DemoHuman1: 'Salut Amber! Nikita \u00e0 l\'appareil. Comment puis-je vous aider aujourd\'hui?',
                        beacon1DemoHuman2: 'Bonjour! Je voulais conna\u00eetre le statut de ma derni\u00e8re commande.',
                        beacon1DemoHuman3: 'Le num\u00e9ro de commande est #10283089',
                        beacon2Title: 'Restez organis\u00e9 automatiquement',
                        beacon2Tab1Title: 'Assignez la bonne personne \u00e0 la bonne t\u00e2che',
                        beacon2Tab1Body: 'Routez automatiquement chaque ticket vers le coll\u00e8gue le plus adapt\u00e9 \u00e0 le r\u00e9soudre rapidement.',
                        beacon2Tab2Title: 'Ne manquez jamais les messages importants',
                        beacon2Tab2Body: 'Gardez les conversations urgentes visibles avec des priorit\u00e9s claires et des alertes intelligentes.',
                        beacon2Tab3Title: 'Simplifiez la file pour votre \u00e9quipe',
                        beacon2Tab3Body: 'Aidez tout le monde \u00e0 \u00eatre plus efficace avec des Vues personnalis\u00e9es qui regroupent les conversations.',
                        beacon3TitlePrefix: 'Tout ce dont votre \u00e9quipe support a besoin',
                        beacon3TitleEmphasis: 'au m\u00eame endroit',
                        beacon3Tab1Title: 'Copilote IA pour chaque agent',
                        beacon3Tab1Body: 'L\'IA lit toute la conversation, g\u00e9n\u00e8re une r\u00e9ponse sugg\u00e9r\u00e9e selon le ton choisi et r\u00e9sume l\'historique complet du ticket.',
                        beacon3Tab2Title: 'Routage intelligent, suivi SLA en direct',
                        beacon3Tab2Body: 'Chaque ticket est auto-assign\u00e9 au meilleur agent disponible, pendant que les comptes \u00e0 rebours SLA et alertes de d\u00e9passement gardent les temps de r\u00e9ponse sous contr\u00f4le.',
                        beacon3Tab3Title: 'Z\u00e9ro friction pour les clients',
                        beacon3Tab3Body: 'Aucun compte requis. Les clients v\u00e9rifient par e-mail, re\u00e7oivent un lien de suivi et peuvent suivre ou r\u00e9pondre depuis n\'importe quel appareil.',

                        /* Navbar */
                        products: 'Produits',
                        solutions: 'Solutions',
                        resources: 'Ressources',
                        pricing: 'Tarifs',
                        companyMenu: 'Entreprise',
                        tryFree: 'Inscription gratuite',
                        viewDemo: 'Connexion',
                        dashboard: 'Tableau de bord',
                        platform: 'Plateforme',
                        platformOverview: 'Aper\u00e7u de la plateforme',
                        integrations: 'Int\u00e9grations',
                        latestInnovations: 'Derni\u00e8res innovations',
                        appMarketplace: 'Marketplace d\'apps',
                        developers: 'D\u00e9veloppeurs',
                        trending: 'Tendances',
                        trendItem1: 'Sommet virtuel HD AI 2026',
                        trendDesc1: 'Un \u00e9v\u00e9nement mondial pour les leaders CX, IT, RH.',
                        trendItem2: 'Co\u00fbts cach\u00e9s de la complexit\u00e9',
                        trendDesc2: 'D\u00e9couvrez la taxe de complexit\u00e9 IT qui co\u00fbte cher.',
                        trendItem3: 'HD s\'associe aux meilleures \u00e9quipes',
                        trendDesc3: 'D\u00e9couvrez comment HD alimente des partenariats mondiaux.',
                        navProductFeatureTitle: 'D\u00e9couvrez Freddy IA',
                        navProductFeatureBadge: 'NOUVEAU',
                        navProductFeatureDescription: 'Une IA agentique qui raisonne, agit et r\u00e9sout',
                        navProductFeatureCta: 'Explorer Freddy IA',
                        productCard1Title: 'Freshservice',
                        productCard1Desc: 'Service desk IT et employ\u00e9s moderne.',
                        productCard2Title: 'Freshdesk Omni',
                        productCard2Desc: 'Service client omnicanal propuls\u00e9 par l\'IA.',
                        productCard3Title: 'Freshdesk',
                        productCard3Desc: 'Ticketing support simple pour \u00e9quipes en croissance.',
                        productLearnMore: 'En savoir plus',
                        productFeatured: '\u00c0 la une',
                        productTour: 'Tour du produit',
                        productTourDesc1: 'Voyez comment les \u00e9quipes r\u00e9solvent plus vite.',
                        productTourDesc2: 'Explorez l\'automatisation sur tous les canaux.',
                        productTourDesc3: 'D\u00e9couvrez un flux ticket plus rapide en minutes.',
                        productWhatsNew: 'Nouveaut\u00e9s',
                        productUpdateDesc: 'Derni\u00e8res am\u00e9liorations IA et int\u00e9grations.',
                        productAllTrials: 'Voir tous les essais produits',
                        companyAbout: '\u00c0 propos',
                        companyAboutDesc: 'D\u00e9couvrez notre mission, histoire et valeurs.',
                        companyCareers: 'Carri\u00e8res',
                        companyCareersDesc: 'Cr\u00e9ez des produits qui aident les \u00e9quipes.',
                        companyHelpCenterDesc: 'Parcourez nos guides, FAQ et ressources d\'assistance.',
                        companyContactDesc: 'Contactez notre \u00e9quipe pour vos questions commerciales ou support.',
                        companyPartnerDesc: 'D\u00e9veloppez-vous avec notre r\u00e9seau mondial.',
                        navResourceFeatureTitle: 'Apprenez avec des ressources concr\u00e8tes',
                        navResourceFeatureDescription: 'Playbooks, documentation et guides pour lancer de meilleurs workflows support.',
                        navResourceFeatureCta: 'Explorer les ressources',
                        byTeam: 'Par \u00e9quipe',
                        customerService: 'Service client',
                        itSupport: 'Support IT',
                        hrTeams: '\u00c9quipes RH',
                        salesTeams: '\u00c9quipes commerciales',
                        bySize: 'Par taille d\'entreprise',
                        enterprise: 'Entreprise',
                        midMarket: 'March\u00e9 interm\u00e9diaire',
                        smallBusiness: 'Petite entreprise',
                        startups: 'Startups',
                        learn: 'Apprendre',
                        blog: 'Blog',
                        documentation: 'Documentation',
                        webinars: 'Webinaires',
                        academy: 'Acad\u00e9mie',
                        connect: 'Connecter',
                        community: 'Communaut\u00e9',
                        events: '\u00c9v\u00e9nements',
                        partnerProgram: 'Programme partenaire',
                        support: 'Assistance',

                        /* Utility Bar */
                        utilitySignIn: 'Se connecter',
                        utilityLogout: 'Se déconnecter',
                        utilityHelpCenter: 'Centre d\'aide',
                        utilityCompany: 'Entreprise',
                        utilityContactUs: 'Nous contacter',

                        /* Footer */
                        footerTagline: 'Un helpdesk moderne pour des \u00e9quipes modernes.',
                        footerProducts: 'Produits',
                        footerPlatformOverview: 'Aper\u00e7u de la plateforme',
                        footerIntegrations: 'Int\u00e9grations',
                        footerMarketplace: 'Marketplace d\'apps',
                        footerDevelopers: 'D\u00e9veloppeurs',
                        footerSolutions: 'Solutions',
                        footerCustomerService: 'Service client',
                        footerItSupport: 'Support IT',
                        footerHrTeams: '\u00c9quipes RH',
                        footerSalesTeams: '\u00c9quipes commerciales',
                        footerResources: 'Ressources',
                        footerBlog: 'Blog',
                        footerDocumentation: 'Documentation',
                        footerWebinars: 'Webinaires',
                        footerCommunity: 'Communaut\u00e9',
                        footerCompany: 'Entreprise',
                        footerAbout: '\u00c0 propos',
                        footerCareers: 'Carri\u00e8res',
                        footerContact: 'Contact',
                        footerPrivacy: 'Politique de confidentialit\u00e9',
                        footerRights: 'Tous droits r\u00e9serv\u00e9s.',
                        footerColProduct: 'Produit',
                        footerLinkDashboard: 'Tableau de bord',
                        footerLinkFeatures: 'Fonctionnalit\u00e9s',
                        footerLinkDiscover: 'D\u00e9couvrir',
                        footerLinkFooter: 'Pied de page',
                        footerColResources: 'Ressources',
                        footerLinkGettingStarted: 'D\u00e9marrage',
                        footerLinkAutomationIdeas: 'Id\u00e9es d\'automatisation',
                        footerLinkCustomerStories: 'T\u00e9moignages clients',
                        footerLinkBrandAssets: 'Ressources de marque',
                        footerColQuickLinks: 'Liens rapides',
                        footerLinkHome: 'Accueil',
                        footerLinkProductTour: 'Tour du produit',
                        footerLinkTestimonials: 'T\u00e9moignages',
                        footerLinkFooterLayout: 'Mise en page du footer',
                        footerColCompanySupport: 'Entreprise et support',
                        footerLinkAbout: '\u00c0 propos',
                        footerLinkHelpCenter: 'Centre d\'aide',
                        footerLinkContact: 'Contact',
                        footerLinkStatus: 'Statut',
                        footerBrand: 'Help Desk',

                        /* Notification banner */
                        notificationBannerLine: 'Nous serions ravis de vous aider. Parlez \u00e0 nos',
                        notificationBannerStrong: 'h\u00e9ros du support.',
                        notificationBannerCta: 'Discuter maintenant ->',
                        notificationBannerDismiss: 'Fermer la notification',

                        /* Chatbot widget */
                        chatbotWelcome1: 'Bienvenue sur notre Helpdesk! Nous sommes l\u00e0 pour vous aider avec toutes vos questions. Comment pouvons-nous vous aider aujourd\'hui?',
                        chatbotWelcome2: 'Bonjour! Besoin d\'un coup de main? Nous sommes pr\u00eats \u00e0 vous aider tout de suite.',
                        chatbotWelcome3: 'Bon retour! Nous vous attendions. Que peut faire notre \u00e9quipe support pour vous aujourd\'hui?',
                        chatbotWelcome4: 'Salut! Merci de nous avoir contact\u00e9s. Dites-nous comment nous pouvons vous simplifier la journ\u00e9e.',
                        chatbotWelcome5: 'Bonjour! Nous sommes l\u00e0 pour vous offrir un support rapide et convivial. Que puis-je faire pour vous?',
                        chatbotNoConversationsTitle: 'Aucune conversation pour le moment',
                        chatbotNoConversationsBody: 'Touchez ci-dessous pour d\u00e9marrer une conversation.<br>Nous vous aiderons tout de suite!',
                        chatbotStartedPrefix: 'Commenc\u00e9e',
                        chatbotEnded: 'Termin\u00e9e',
                        chatbotRemoveConversation: 'Supprimer la conversation',
                        chatbotNewConversation: 'Nouvelle conversation',
                        chatbotBuiltWith: 'PROPULS\u00c9 PAR HELPDESK AI',
                        chatbotRepliesFast: 'R\u00e9pond g\u00e9n\u00e9ralement instantan\u00e9ment',
                        chatbotQuickActions: 'Actions rapides',
                        chatbotQuickReply1: 'Comment fonctionne le syst\u00e8me de tickets?',
                        chatbotQuickReply2: 'Puis-je l\'essayer gratuitement?',
                        chatbotQuickReply3: 'Quelles int\u00e9grations prenez-vous en charge?',
                        chatbotQuickReply4: 'Parlez-moi des tarifs',
                        chatbotInputPlaceholder: 'Tapez votre message...',

                        /* About page */
                        aboutTypewriter: '\u00c0 propos',
                        aboutHeroTitle: 'Construire un logiciel de support qui reste humain \u00e0 grande \u00e9chelle',
                        aboutHeroDescription: 'HelpDesk a \u00e9t\u00e9 cr\u00e9\u00e9 pour supprimer le chaos du service client. Nous avons construit une plateforme unique o\u00f9 les \u00e9quipes peuvent router les tickets intelligemment, r\u00e9pondre plus vite gr\u00e2ce \u00e0 l\'IA et clore chaque conversation avec confiance.',
                        aboutHeroCtaPrimary: 'Parler \u00e0 notre \u00e9quipe',
                        aboutHeroCtaSecondary: 'Explorer le centre d\'aide',
                        aboutPillar1Title: 'Port\u00e9e mondiale',
                        aboutPillar1Body: 'Des \u00e9quipes de tous les fuseaux horaires font confiance \u00e0 HelpDesk pour garder leurs op\u00e9rations actives.',
                        aboutPillar2Title: 'Con\u00e7u pour l\'\u00e9chelle',
                        aboutPillar2Body: 'Une architecture de niveau entreprise pens\u00e9e d\u00e8s le premier jour pour la croissance.',
                        aboutPillar3Title: 'Confidentialit\u00e9 d\'abord',
                        aboutPillar3Body: 'Vos donn\u00e9es restent les v\u00f4tres avec une isolation stricte et une transparence totale.',
                        aboutPillar4Title: 'Centr\u00e9 sur l\'humain',
                        aboutPillar4Body: 'Une IA qui renforce les agents sans jamais remplacer le lien humain.',
                        aboutStoryTitle: 'Notre histoire',
                        aboutStoryBody1: 'Nous sommes partis d\'un constat: les \u00e9quipes support g\u00e9raient des demandes critiques \u00e0 travers des bo\u00eetes mail, des feuilles de calcul et des workflows fragiles. Les sujets \u00e9taient retard\u00e9s, la responsabilit\u00e9 \u00e9tait floue et les managers manquaient de visibilit\u00e9 fiable. Nous avons repens\u00e9 le support comme un syst\u00e8me d\'exploitation unique.',
                        aboutStoryBody2: 'Aujourd\'hui, les entreprises d\u00e9ploient HelpDesk en quelques heures, pas en plusieurs mois. Les admins d\u00e9finissent cat\u00e9gories, SLA, r\u00e8gles d\'automatisation et groupes d\'\u00e9quipe. Les agents re\u00e7oivent des suggestions IA contextuelles et des r\u00e9sum\u00e9s instantan\u00e9s. Les clients re\u00e7oivent des mises \u00e0 jour sans friction de compte. Chaque action est tra\u00e7able, mesurable et pens\u00e9e pour l\'\u00e9chelle.',
                        aboutDifferenceTitle: 'Ce qui rend HelpDesk diff\u00e9rent',
                        aboutDifference1Title: 'Isolation multi-tenant',
                        aboutDifference1Body: 'Chaque entreprise dispose de son propre sous-domaine, de sa port\u00e9e de donn\u00e9es et d\'un mod\u00e8le de configuration avec une s\u00e9paration stricte.',
                        aboutDifference2Title: 'Exp\u00e9rience client sans connexion',
                        aboutDifference2Body: 'Les clients se v\u00e9rifient par e-mail puis continuent via un lien de suivi, ce qui r\u00e9duit l\'abandon et la friction.',
                        aboutDifference3Title: 'Moteur de routage intelligent',
                        aboutDifference3Body: 'Les tickets sont rout\u00e9s par cat\u00e9gorie, sous-cat\u00e9gorie, sp\u00e9cialit\u00e9s, charge et disponibilit\u00e9 en quasi temps r\u00e9el.',
                        aboutDifference4Title: 'IA copilote, pas remplacement',
                        aboutDifference4Body: 'Les agents gardent le contr\u00f4le pendant que l\'IA g\u00e8re les r\u00e9sum\u00e9s, suggestions et brouillons r\u00e9p\u00e9titifs.',
                        aboutGrowthTitle: 'Comment les \u00e9quipes grandissent avec nous',
                        aboutGrowthPhase1Label: 'Phase 1',
                        aboutGrowthPhase1Title: 'Lancer en quelques jours',
                        aboutGrowthPhase1Body: 'Les admins pilotent l\'onboarding, configurent les cat\u00e9gories de tickets et la politique SLA, puis int\u00e8grent le widget formulaire avec un seul script.',
                        aboutGrowthPhase2Label: 'Phase 2',
                        aboutGrowthPhase2Title: 'Automatiser les op\u00e9rations',
                        aboutGrowthPhase2Body: 'Les r\u00e8gles assignent les tickets, d\u00e9clenchent des alertes et escaladent automatiquement les risques SLA pendant que les managers suivent les tableaux de bord en direct.',
                        aboutGrowthPhase3Label: 'Phase 3',
                        aboutGrowthPhase3Title: 'Optimiser la performance',
                        aboutGrowthPhase3Body: 'Les \u00e9quipes affinent les workflows avec l\'analytique, la sant\u00e9 des cat\u00e9gories et des classements agents qui r\u00e9v\u00e8lent rapidement les goulots d\'\u00e9tranglement.',
                        aboutNoteTitle: 'Un mot de notre \u00e9quipe',
                        aboutNoteBody1: 'Nous con\u00e7evons HelpDesk pour qu\'il soit clair, rapide et fiable d\u00e8s le premier jour. Nous soignons les d\u00e9tails op\u00e9rationnels: qualit\u00e9 des handoffs, coh\u00e9rence des r\u00e9ponses, visibilit\u00e9 des escalades et maintenabilit\u00e9 long terme. Votre \u00e9quipe support ne doit jamais \u00eatre frein\u00e9e par l\'outil; elle doit \u00eatre amplifi\u00e9e.',
                        aboutNoteBody2: 'Que vous lanciez votre premier service support ou que vous montiez en \u00e9chelle sur plusieurs r\u00e9gions, nos \u00e9quipes produit et customer success vous aident \u00e0 construire des workflows durables.',
                        aboutVisionTitle: 'Vision produit approfondie',
                        aboutVisionBody1: 'Nous pensons qu\'un syst\u00e8me de support ne doit pas seulement suivre des demandes, mais coordonner des r\u00e9sultats. Chaque interaction doit apporter du contexte structur\u00e9, une responsabilit\u00e9 claire, des d\u00e9lais actionnables et des signaux de qualit\u00e9 mesurables. Dans HelpDesk, chaque ticket est li\u00e9 \u00e0 des cat\u00e9gories, priorit\u00e9s, horloges SLA et logique de routage op\u00e9rationnelle.',
                        aboutVisionBody2: 'Quand le volume support augmente, la complexit\u00e9 augmente plus vite que les effectifs. Nous avons con\u00e7u HelpDesk pour absorber cette complexit\u00e9 avec des valeurs par d\u00e9faut intelligentes et une automatisation configurable. R\u00e8gles d\'assignation, escalades, alertes SLA et actions de cycle de vie travaillent ensemble pour r\u00e9duire l\'orchestration manuelle.',
                        aboutVisionBody3: 'Nous accordons aussi une grande importance \u00e0 la qualit\u00e9 d\'exp\u00e9rience pour chaque r\u00f4le. Les admins ont besoin de contr\u00f4le et de visibilit\u00e9. Les agents ont besoin de vitesse et de contexte. Les clients ont besoin d\'un parcours fluide. C\'est pourquoi nous avons unifi\u00e9 suivi sans connexion, r\u00e9sum\u00e9s IA, notes de collaboration et outils de connaissance dans un seul workflow.',
                        aboutInfrastructureTitle: 'Comment nous concevons l\'infrastructure support',
                        aboutInfrastructure1Title: 'Fiabilit\u00e9 d\'abord',
                        aboutInfrastructure1Body: 'Les workflows sont con\u00e7us pour une ex\u00e9cution pr\u00e9visible. Assignation, escalade, notification et cl\u00f4ture suivent une s\u00e9quence d\u00e9terministe pour maintenir la confiance lors des pics de volume.',
                        aboutInfrastructure2Title: 'Efficacit\u00e9 op\u00e9rateur',
                        aboutInfrastructure2Body: 'Les agents acc\u00e8dent instantan\u00e9ment au contexte via les r\u00e9sum\u00e9s IA, des \u00e9tats de ticket clairs et des r\u00e9f\u00e9rences \u00e0 la base de connaissances. Cela r\u00e9duit le temps de r\u00e9ponse et les allers-retours inutiles.',
                        aboutInfrastructure3Title: 'R\u00e9sultats visibles',
                        aboutInfrastructure3Body: 'Le management obtient une visibilit\u00e9 op\u00e9rationnelle compl\u00e8te via rapports, sant\u00e9 SLA, tendances par cat\u00e9gorie et jeux de donn\u00e9es exportables pour le pilotage quotidien et trimestriel.',
                        aboutCultureTitle: 'Au coeur de notre culture support mondiale',
                        aboutCultureBody: 'Nous op\u00e9rons comme une seule \u00e9quipe distribu\u00e9e, avec des standards partag\u00e9s et une flexibilit\u00e9 locale d\'ex\u00e9cution. Produit, success et ing\u00e9nierie collaborent en continu sur les playbooks d\'escalade, les templates de workflow et l\'architecture de connaissance afin d\'assurer des r\u00e9sultats coh\u00e9rents.',
                        aboutCommitmentTitle: 'Notre engagement',
                        aboutCommitmentBody1: 'Nous nous engageons \u00e0 construire un logiciel support rapide, observable et adaptable \u00e0 mesure que votre organisation grandit. Nous livrons des fonctionnalit\u00e9s qui r\u00e9duisent la friction op\u00e9rationnelle, au lieu d\'ajouter de la complexit\u00e9 d\'interface.',
                        aboutCommitmentBody2: 'Nous nous engageons \u00e0 la transparence sur le fonctionnement de l\'automatisation et la g\u00e9n\u00e9ration des suggestions IA. Les \u00e9quipes doivent comprendre et contr\u00f4ler le syst\u00e8me, pas deviner son comportement.',
                        aboutCommitmentBody3: 'Nous nous engageons \u00e0 \u00eatre un partenaire durable. Notre \u00e9quipe accompagne la strat\u00e9gie d\'impl\u00e9mentation, la migration et l\'optimisation continue pour faire progresser votre support dans le temps.',

                        /* Contact page */
                        contactTypewriter: 'Contact',
                        contactHeroTitle: 'Lancez un meilleur support, plus vite, avec nous',
                        contactHeroDescription: 'Dites-nous ce dont vous avez besoin et notre \u00e9quipe vous guide sur la mise en place, la migration, la strat\u00e9gie d\'automatisation et l\'int\u00e9gration des widgets.',
                        contactFormTitle: 'Envoyer un message',
                        contactFormRequiredNote: 'Les champs marqu\u00e9s d\'un * sont obligatoires.',
                        contactSuccessMessage: 'Message envoy\u00e9 avec succ\u00e8s. Nous vous r\u00e9pondrons rapidement.',
                        contactFieldName: 'Nom complet *',
                        contactFieldNamePlaceholder: 'Jane Doe',
                        contactFieldEmail: 'E-mail professionnel *',
                        contactFieldEmailPlaceholder: 'jane@company.com',
                        contactFieldCompany: 'Nom de l\'entreprise *',
                        contactFieldCompanyPlaceholder: 'Acme Inc',
                        contactFieldTeamSize: 'Taille de l\'\u00e9quipe',
                        contactTeamSizeOption0: 'S\u00e9lectionnez une option',
                        contactTeamSizeOption1: '1-5 agents',
                        contactTeamSizeOption2: '6-20 agents',
                        contactTeamSizeOption3: '21-50 agents',
                        contactTeamSizeOption4: '50+ agents',
                        contactFieldTopic: 'Sujet *',
                        contactTopicOption0: 'Choisissez un sujet',
                        contactTopicOption1: 'R\u00e9server une d\u00e9mo produit',
                        contactTopicOption2: 'Migration et onboarding',
                        contactTopicOption3: 'Tarifs et offres',
                        contactTopicOption4: 'Support technique',
                        contactFieldMessage: 'Message *',
                        contactFieldMessagePlaceholder: 'Parlez-nous de vos objectifs support, du volume de tickets et de votre workflow actuel.',
                        contactResponseNote: 'Nous r\u00e9pondons sous un jour ouvr\u00e9.',
                        contactSubmit: 'Envoyer le message',
                        contactSalesTitle: 'Parler aux ventes',
                        contactSalesBody: 'Pour les tarifs et la planification d\'impl\u00e9mentation.',
                        contactSupportTitle: 'Support client',
                        contactSupportBody: 'Les clients existants peuvent obtenir une aide rapide de notre \u00e9quipe support.',
                        contactChecklistTitle: 'Checklist de d\u00e9marrage rapide',
                        contactChecklist1: '1. Partagez votre volume actuel de tickets et vos canaux.',
                        contactChecklist2: '2. Nous cartographions cat\u00e9gories, SLA et r\u00e8gles d\'automatisation.',
                        contactChecklist3: '3. Vos widgets passent en production avec une seule balise script.',
                        contactOfficesTitle: 'Nos bureaux dans le monde',
                        contactWhyTitle: 'Pourquoi les \u00e9quipes nous contactent avant le lancement',
                        contactWhyBody1: 'La plupart des \u00e9quipes nous contactent lorsqu\'elles remplacent des workflows support fragment\u00e9s et ont besoin d\'un plan de d\u00e9ploiement fiable. Nous aidons \u00e0 d\u00e9finir les matrices de priorit\u00e9, la propri\u00e9t\u00e9 des files et les limites d\'escalade avant le premier ticket en production.',
                        contactWhyBody2: 'Nous cartographions aussi le parcours client de bout en bout: points de soumission, mod\u00e8les de r\u00e9ponse, auto-r\u00e9ponses, seuils SLA et politique de cl\u00f4ture. Le r\u00e9sultat: une op\u00e9ration support coh\u00e9rente sur tous les canaux.',
                        contactAfterTitle: 'Ce qui se passe apr\u00e8s votre prise de contact',
                        contactAfter1Title: 'Appel de d\u00e9couverte',
                        contactAfter1Body: 'Nous passons en revue vos canaux, volume attendu, structure d\'\u00e9quipe et objectifs de r\u00e9ponse pour concevoir un d\u00e9ploiement pragmatique.',
                        contactAfter2Title: 'Plan de configuration',
                        contactAfter2Body: 'Cat\u00e9gories, SLA, r\u00e8gles d\'automatisation et branding du widget sont pr\u00e9par\u00e9s selon votre workflow.',
                        contactAfter3Title: 'Support de mise en production',
                        contactAfter3Body: 'Nous restons avec votre \u00e9quipe pendant le lancement, surveillons le premier trafic et ajustons le routage ou les flux de r\u00e9ponse si n\u00e9cessaire.',

                        /* Help center page */
                        helpTypewriter: 'Centre d\'aide',
                        helpHeroTitle: 'Des r\u00e9ponses pour les admins, les agents et les clients au m\u00eame endroit',
                        helpHeroDescription: 'D\u00e9couvrez comment HelpDesk g\u00e8re le routage des tickets, le copilote IA, l\'automatisation SLA, les widgets int\u00e9grables et les workflows de reporting.',
                        helpSearchLabel: 'Rechercher des r\u00e9ponses',
                        helpSearchPlaceholder: 'Exemple: SLA, automatisation, chatbot, routage des tickets',
                        helpPopularAnswersTitle: 'R\u00e9ponses populaires',
                        helpShowMoreAnswers: 'Afficher 10 r\u00e9ponses suppl\u00e9mentaires',
                        helpJourneyTitle: 'Parcours du ticket',
                        helpJourney1: '1. Le client soumet un probl\u00e8me via le widget.',
                        helpJourney2: '2. L\'automatisation route vers le groupe + le meilleur agent.',
                        helpJourney3: '3. L\'agent re\u00e7oit un r\u00e9sum\u00e9 IA et une suggestion.',
                        helpJourney4: '4. La r\u00e9solution lance le cycle de fermeture automatique.',
                        helpRoleWorkflowsTitle: 'Workflows par r\u00f4le',
                        helpRoleAdmin: 'Admin: configure cat\u00e9gories, SLA, groupes et r\u00e8gles.',
                        helpRoleAgent: 'Agent: g\u00e8re la file, les notes, les r\u00e9ponses et les liens KB.',
                        helpRoleCustomer: 'Client: v\u00e9rifie son e-mail et suit sans connexion.',
                        helpAssistanceTitle: 'Besoin d\'aide directe?',
                        helpAssistanceBody: 'Pour la mise en place de compte, la migration et les workflows personnalis\u00e9s, contactez notre \u00e9quipe.',
                        helpAssistancePrimaryCta: 'Contacter l\'\u00e9quipe',
                        helpAssistanceSecondaryCta: 'E-mail support',
                        helpLifecycleTitle: 'Cycle support complet dans une seule plateforme',
                        helpLifecycleBody1: 'HelpDesk est con\u00e7u pour couvrir tout le parcours, de la soumission \u00e0 l\'archive. Les nouveaux sujets entrent via votre widget de marque, sont cat\u00e9goris\u00e9s et prioris\u00e9s, puis rout\u00e9s vers la bonne file pour action rapide. Les agents collaborent avec notes priv\u00e9es, suggestions IA et r\u00e9f\u00e9rences de connaissance pendant que les clients suivent par e-mail et lien de tracking.',
                        helpLifecycleBody2: 'Cette approche r\u00e9duit la fragmentation op\u00e9rationnelle. Au lieu de changer d\'outil pour le routage, la collaboration, la visibilit\u00e9 SLA et la communication client, chaque r\u00f4le travaille au m\u00eame endroit avec un \u00e9tat coh\u00e9rent et une source de v\u00e9rit\u00e9 partag\u00e9e.',
                        helpPlaybooksTitle: 'Playbooks op\u00e9rationnels pour chaque r\u00f4le',
                        helpPlaybookAdminTitle: 'Playbook admin',
                        helpPlaybookAdminBody: 'Configurez les cat\u00e9gories, paliers SLA, r\u00e8gles d\'assignation et politiques de notification. Surveillez les d\u00e9passements en direct et optimisez le d\u00e9bit de l\'\u00e9quipe via des rapports centralis\u00e9s.',
                        helpPlaybookAgentTitle: 'Playbook agent',
                        helpPlaybookAgentBody: 'Prenez les files tri\u00e9es par priorit\u00e9, consultez le r\u00e9sum\u00e9 IA, composez une r\u00e9ponse avec suggestions optionnelles, joignez des fichiers, ins\u00e9rez des liens KB et cl\u00f4turez avec confiance.',
                        helpPlaybookCustomerTitle: 'Playbook client',
                        helpPlaybookCustomerBody: 'Soumettez un probl\u00e8me sans inscription, v\u00e9rifiez par e-mail, suivez via le lien de tracking, r\u00e9pondez depuis la bo\u00eete mail et recevez des mises \u00e0 jour claires \u00e0 chaque changement de statut.',
                        helpFaq1Q: 'Comment fonctionne le support client sans connexion?',
                        helpFaq1A: 'Les clients soumettent un ticket via le widget du site, v\u00e9rifient leur e-mail puis re\u00e7oivent un lien de suivi. Ils peuvent suivre les mises \u00e0 jour et r\u00e9pondre sans cr\u00e9er de compte.',
                        helpFaq2Q: 'Comment les tickets sont-ils rout\u00e9s vers les bonnes personnes?',
                        helpFaq2A: 'Le moteur d\'automatisation applique des r\u00e8gles selon la cat\u00e9gorie, la sous-cat\u00e9gorie, la priorit\u00e9, le groupe assign\u00e9 et la disponibilit\u00e9, puis choisit l\'agent le plus adapt\u00e9 selon sp\u00e9cialit\u00e9s et charge.',
                        helpFaq3Q: 'Que fait le copilote IA pour les agents?',
                        helpFaq3A: 'L\'IA lit toute la conversation, g\u00e9n\u00e8re un r\u00e9sum\u00e9 concis et propose des r\u00e9ponses modifiables dans le ton choisi. Les agents peuvent r\u00e9g\u00e9n\u00e9rer, affiner ou ignorer instantan\u00e9ment.',
                        helpFaq4Q: 'Comment le suivi SLA \u00e9vite-t-il les d\u00e9lais manqu\u00e9s?',
                        helpFaq4A: 'Chaque ticket re\u00e7oit une \u00e9ch\u00e9ance selon la politique de priorit\u00e9. Des comptes \u00e0 rebours affichent le risque et des notifications de d\u00e9passement sont envoy\u00e9es aux agents et admins concern\u00e9s.',
                        helpFaq5Q: 'Les administrateurs peuvent-ils configurer l\'automatisation sans code?',
                        helpFaq5A: 'Oui. Les admins cr\u00e9ent des r\u00e8gles condition-action depuis un panneau visuel. Ils peuvent assigner des agents/groupes, ajuster la priorit\u00e9, d\u00e9clencher des auto-r\u00e9ponses et escalader selon SLA ou r\u00e8gles VIP.',
                        helpFaq6Q: 'Quelle automatisation de cycle de vie intervient apr\u00e8s la r\u00e9solution?',
                        helpFaq6A: 'Les tickets r\u00e9solus d\u00e9clenchent des notifications client, des rappels \u00e0 24h et une fermeture automatique \u00e0 48h. Les tickets ferm\u00e9s peuvent \u00eatre rouverts via des fen\u00eatres li\u00e9es puis archiv\u00e9s.',
                        helpFaq7Q: 'Comment la base de connaissances aide-t-elle agents et clients?',
                        helpFaq7A: 'Les clients peuvent parcourir/rechercher les articles publics sous /kb. Les agents peuvent rechercher la base de connaissances directement dans les outils de r\u00e9ponse et ins\u00e9rer des liens sans quitter la conversation.',
                        helpFaq8Q: 'Quels widgets peuvent \u00eatre int\u00e9gr\u00e9s sur notre site?',
                        helpFaq8A: 'HelpDesk fournit un widget formulaire, un widget chatbot IA et un widget de recherche KB. Chacun utilise un code d\'int\u00e9gration par script et se g\u00e8re depuis une zone d\'int\u00e9grations unique.',
                        helpFaq9Q: 'Comment les donn\u00e9es sont-elles isol\u00e9es en mode multi-tenant?',
                        helpFaq9A: 'Chaque entreprise fonctionne sur son propre sous-domaine et son propre jeu de donn\u00e9es. Tickets, clients, param\u00e8tres et analytics restent isol\u00e9s sans acc\u00e8s crois\u00e9.',
                        helpFaq10Q: 'Quels rapports sont disponibles pour l\'analyse de performance?',
                        helpFaq10A: 'Les rapports incluent tendances globales, performance agents, analyse de tickets et sant\u00e9 des cat\u00e9gories. Les \u00e9quipes peuvent exporter en CSV/PDF et suivre classements et comportements de r\u00e9solution.',
                        helpFaq11Q: 'Les agents peuvent-ils mettre \u00e0 jour plusieurs tickets en masse?',
                        helpFaq11A: 'Oui. Agents et admins peuvent assigner en masse, changer le statut, ajuster la priorit\u00e9 et effectuer des actions batch depuis des vues filtr\u00e9es pour acc\u00e9l\u00e9rer la maintenance des files.',
                        helpFaq12Q: 'Comment fonctionnent les vues enregistr\u00e9es pour les filtres r\u00e9currents?',
                        helpFaq12A: 'Toute combinaison de filtres avanc\u00e9s peut \u00eatre enregistr\u00e9e comme vue nomm\u00e9e. Les \u00e9quipes peuvent les rouvrir instantan\u00e9ment pour suivre des cat\u00e9gories, des files \u00e0 risque SLA ou des charges sp\u00e9cifiques agent.',
                        helpFaq13Q: 'Comment les notes internes sont-elles s\u00e9par\u00e9es des r\u00e9ponses client?',
                        helpFaq13A: 'Les notes internes sont stock\u00e9es dans la m\u00eame timeline ticket mais marqu\u00e9es priv\u00e9es. Elles sont visibles uniquement pour les agents/admins et ne sont jamais envoy\u00e9es aux clients.',
                        helpFaq14Q: 'Peut-on utiliser des permissions bas\u00e9es sur les r\u00f4les entre \u00e9quipes?',
                        helpFaq14A: 'Oui. Les admins peuvent contr\u00f4ler les capacit\u00e9s agents, restreindre les actions sensibles et d\u00e9limiter les acc\u00e8s par r\u00f4le ou groupe pour garder des op\u00e9rations coh\u00e9rentes et s\u00e9curis\u00e9es.',
                        helpFaq15Q: 'Comment fonctionne le routage des clients VIP?',
                        helpFaq15A: 'Les conditions VIP peuvent d\u00e9clencher des surcharges de priorit\u00e9, des groupes de routage sp\u00e9cifiques et des notifications personnalis\u00e9es afin que les clients \u00e0 forte valeur re\u00e7oivent un traitement plus rapide.',
                        helpFaq16Q: 'Peut-on personnaliser les champs ticket dans le widget formulaire?',
                        helpFaq16A: 'Les admins peuvent configurer les champs visibles, les obligations, les contr\u00f4les cat\u00e9gorie/sous-cat\u00e9gorie, les exigences t\u00e9l\u00e9phone et les valeurs par d\u00e9faut depuis les param\u00e8tres du widget.',
                        helpFaq17Q: 'Que se passe-t-il si aucun agent n\'est disponible \u00e0 la cr\u00e9ation du ticket?',
                        helpFaq17A: 'Le ticket reste non assign\u00e9, l\'intention de routage est conserv\u00e9e et les admins sont notifi\u00e9s imm\u00e9diatement pour r\u00e9soudre les manques de couverture sans perdre le contexte.',
                        helpFaq18Q: 'Comment fonctionnent les pr\u00e9f\u00e9rences de notification par agent?',
                        helpFaq18A: 'Chaque agent peut configurer les \u00e9v\u00e9nements qu\'il re\u00e7oit. Les notifications sont regroup\u00e9es par type et date, avec des vues d\u00e9di\u00e9es aux risques SLA pour un triage rapide.',
                        helpFaq19Q: 'Les \u00e9quipes peuvent-elles exporter les donn\u00e9es pour audits et revues de direction?',
                        helpFaq19A: 'Oui. Les listes de tickets, vues de performance et rapports de cat\u00e9gorie peuvent \u00eatre export\u00e9s en CSV ou PDF pour la gouvernance mensuelle, la planification et la conformit\u00e9.',
                        helpFaq20Q: 'Comment le chatbot passe-t-il \u00e0 la cr\u00e9ation de ticket?',
                        helpFaq20A: 'Si le chatbot ne peut pas r\u00e9soudre apr\u00e8s le nombre de tours configur\u00e9, il propose un passage guid\u00e9 vers la cr\u00e9ation de ticket en conservant le contexte pour \u00e9viter au client de tout ressaisir.',
                    },
                };
                return dict[this.lang]?.[key] ?? key;
            },

            init() {
                /* Sync dark class on <html> whenever darkMode changes */
                this._watchDark();
            },

            _watchDark() {
                /* Alpine.effect runs reactively whenever darkMode changes */
                Alpine.effect(() => {
                    document.documentElement.classList.toggle('dark', this.darkMode);
                });
            },
        });
    });
</script>

{{ $slot }}